In [6]:
import plotly.express as px
import pandas as pd
import itertools

In [2]:
GloHydroRes = pd.read_excel("/home/shah0012/GloHydroRes/Output_data/GloHydroRes_vs2.xlsx", sheet_name="Data")

In [3]:
interest_countries = ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Turkey']
selected_data = GloHydroRes[GloHydroRes['country'].isin(interest_countries)]

In [4]:
selected_data = selected_data.groupby(['country', "year"])["capacity_mw"].sum().reset_index()

In [5]:
selected_data['year'] = selected_data.year.astype(int)

In [9]:
print(selected_data[selected_data.country == "France"].head(10))
print(selected_data[selected_data.country == "Germany"].head(10))

  country  year  capacity_mw
0  France  1887     9.999000
1  France  1888     9.010000
2  France  1899    57.466260
3  France  1903     3.600000
4  France  1905     8.800000
5  France  1908    86.200000
6  France  1909    21.595000
7  France  1910    78.615924
8  France  1911     7.000000
9  France  1913    57.000000
    country  year  capacity_mw
80  Germany  1905         16.0
81  Germany  1910          8.5
82  Germany  1915         20.0
83  Germany  1919         19.0
84  Germany  1920          3.3
85  Germany  1922         56.3
86  Germany  1923         15.3
87  Germany  1924        287.2
88  Germany  1925         26.0
89  Germany  1926        109.0

In [7]:
full_year_range = range(selected_data.year.min(), selected_data.year.max() + 1)

# Create a DataFrame with all combinations of countries and years
all_combinations = pd.DataFrame(list(itertools.product(interest_countries, full_year_range)), columns=['country', 'year'])

In [12]:
selected_data_updated  = selected_data.set_index(['country', 'year']).reindex(all_combinations, fill_value=0).reset_index()

In [14]:
print(selected_data_updated[selected_data_updated.country == "France"].head(20))
print(selected_data_updated[selected_data_updated.country == "Germany"].head(10))

    country  year  capacity_mw
136  France  1884      0.00000
137  France  1885      0.00000
138  France  1886      0.00000
139  France  1887      9.99900
140  France  1888      9.01000
141  France  1889      0.00000
142  France  1890      0.00000
143  France  1891      0.00000
144  France  1892      0.00000
145  France  1893      0.00000
146  France  1894      0.00000
147  France  1895      0.00000
148  France  1896      0.00000
149  France  1897      0.00000
150  France  1898      0.00000
151  France  1899     57.46626
152  France  1900      0.00000
153  France  1901      0.00000
154  France  1902      0.00000
155  France  1903      3.60000
   country  year  capacity_mw
0  Germany  1884          0.0
1  Germany  1885          0.0
2  Germany  1886          0.0
3  Germany  1887          0.0
4  Germany  1888          0.0
5  Germany  1889          0.0
6  Germany  1890          0.0
7  Germany  1891          0.0
8  Germany  1892          0.0
9  Germany  1893          0.0

In [15]:
#selected_data.groupby("year")["capacity_mw"].cumsum()
selected_data_updated['cumulative_capacity_mw'] = selected_data_updated.groupby('country')["capacity_mw"].cumsum()

In [16]:
print(selected_data_updated[selected_data_updated.country == "France"].head(20))
print(selected_data_updated[selected_data_updated.country == "Germany"].head(10))

    country  year  capacity_mw  cumulative_capacity_mw
136  France  1884      0.00000                 0.00000
137  France  1885      0.00000                 0.00000
138  France  1886      0.00000                 0.00000
139  France  1887      9.99900                 9.99900
140  France  1888      9.01000                19.00900
141  France  1889      0.00000                19.00900
142  France  1890      0.00000                19.00900
143  France  1891      0.00000                19.00900
144  France  1892      0.00000                19.00900
145  France  1893      0.00000                19.00900
146  France  1894      0.00000                19.00900
147  France  1895      0.00000                19.00900
148  France  1896      0.00000                19.00900
149  France  1897      0.00000                19.00900
150  France  1898      0.00000                19.00900
151  France  1899     57.46626                76.47526
152  France  1900      0.00000                76.47526
153  France  1901      0.00000                76.47526
154  France  1902      0.00000                76.47526
155  France  1903      3.60000                80.07526
   country  year  capacity_mw  cumulative_capacity_mw
0  Germany  1884          0.0                     0.0
1  Germany  1885          0.0                     0.0
2  Germany  1886          0.0                     0.0
3  Germany  1887          0.0                     0.0
4  Germany  1888          0.0                     0.0
5  Germany  1889          0.0                     0.0
6  Germany  1890          0.0                     0.0
7  Germany  1891          0.0                     0.0
8  Germany  1892          0.0                     0.0
9  Germany  1893          0.0                     0.0

In [32]:
selected_data_updated["cumulative_capacity_gw"] = selected_data_updated.cumulative_capacity_mw*0.001

In [38]:
#animation_frame = This means year will be used to change the frames. So each year will be a frame.
#animation_group = Each country will represented in each frame.
fig = px.scatter(selected_data_updated, x="year", y="cumulative_capacity_gw", animation_frame="year", 
                 animation_group="country", size="cumulative_capacity_gw", color="country", 
                 hover_name="country", size_max=55, range_x=[selected_data_updated['year'].min(), selected_data_updated['year'].max()], 
                 range_y=[0, selected_data_updated['cumulative_capacity_gw'].max()], 
                 title="Cumulative Capacity Over Time",
                 labels={"cumulative_capacity_gw": "Cumulative Capacity (GW)", "year": "Year"})

fig.update_traces(showlegend=True, marker=dict(size=15))

fig.update_layout(legend_title_text='Country')
fig.show()
fig.write_html("/home/shah0012/GloHydroRes/Figure/animation.html")

In [31]:
input_data = pd.read_csv("/home/shah0012/Extra/data/01 renewable-share-energy.csv")
input_data = input_data.drop(columns=['Code'])

In [35]:
input_data.rename(columns={'Renewables (% equivalent primary energy)': 'renewable_share'}, inplace=True)

In [36]:
interest_countries = ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Turkey']

selected_data = input_data[input_data['Entity'].isin(interest_countries)]

fig = px.scatter(selected_data, x="Year", y="renewable_share", animation_frame="Year", 
                 animation_group="Entity", size="renewable_share", color="Entity", 
                 hover_name="Entity", size_max=55, range_x=[selected_data['Year'].min(), selected_data['Year'].max()], 
                 range_y=[0, selected_data['renewable_share'].max()])

fig.show()

In [34]:
selected_data

              Entity  Year  Renewables (% equivalent primary energy)
1732          France  1965                                 10.584984
1733          France  1966                                 11.602393
1734          France  1967                                  9.537199
1735          France  1968                                 10.092880
1736          France  1969                                  9.634168
...              ...   ...                                       ...
5219  United Kingdom  2017                                 12.948246
5220  United Kingdom  2018                                 14.526468
5221  United Kingdom  2019                                 16.241540
5222  United Kingdom  2020                                 20.078987
5223  United Kingdom  2021                                 17.946543

[342 rows x 3 columns]

In [40]:
selected_data[selected_data["Entity"] == "United Kingdom"]

              Entity  Year  renewable_share
5167  United Kingdom  1965         0.588787
5168  United Kingdom  1966         0.576279
5169  United Kingdom  1967         0.620428
5170  United Kingdom  1968         0.456407
5171  United Kingdom  1969         0.385314
5172  United Kingdom  1970         0.525781
5173  United Kingdom  1971         0.398344
5174  United Kingdom  1972         0.392566
5175  United Kingdom  1973         0.425518
5176  United Kingdom  1974         0.475209
5177  United Kingdom  1975         0.475199
5178  United Kingdom  1976         0.550305
5179  United Kingdom  1977         0.470889
5180  United Kingdom  1978         0.482057
5181  United Kingdom  1979         0.486753
5182  United Kingdom  1980         0.491026
5183  United Kingdom  1981         0.564400
5184  United Kingdom  1982         0.586955
5185  United Kingdom  1983         0.584591
5186  United Kingdom  1984         0.584975
5187  United Kingdom  1985         0.489204
5188  United Kingdom  1986         0.573972
5189  United Kingdom  1987         0.504714
5190  United Kingdom  1988         0.581196
5191  United Kingdom  1989         0.567624
5192  United Kingdom  1990         0.680118
5193  United Kingdom  1991         0.610434
5194  United Kingdom  1992         0.742499
5195  United Kingdom  1993         0.667650
5196  United Kingdom  1994         0.825375
5197  United Kingdom  1995         0.789619
5198  United Kingdom  1996         0.644379
5199  United Kingdom  1997         0.825345
5200  United Kingdom  1998         0.985597
5201  United Kingdom  1999         1.105551
5202  United Kingdom  2000         1.134558
5203  United Kingdom  2001         1.085675
5204  United Kingdom  2002         1.287619
5205  United Kingdom  2003         1.234234
5206  United Kingdom  2004         1.608395
5207  United Kingdom  2005         1.924693
5208  United Kingdom  2006         2.116309
5209  United Kingdom  2007         2.422110
5210  United Kingdom  2008         2.912039
5211  United Kingdom  2009         3.545405
5212  United Kingdom  2010         3.659130
5213  United Kingdom  2011         4.891127
5214  United Kingdom  2012         5.453807
5215  United Kingdom  2013         6.954726
5216  United Kingdom  2014         8.877189
5217  United Kingdom  2015        10.976621
5218  United Kingdom  2016        11.037631
5219  United Kingdom  2017        12.948246
5220  United Kingdom  2018        14.526468
5221  United Kingdom  2019        16.241540
5222  United Kingdom  2020        20.078987
5223  United Kingdom  2021        17.946543